name: 'Publish'


on:
  workflow_dispatch:

  release:
    types: [created]


env:
  SDK_VERSION_8: '8.0.404'
  SDK_VERSION_7: '7.0.410'
  SDK_VERSION_6: '6.0.428'
  SDK_VERSION_5: '5.0.408'
  SDK_VERSION_3: '3.1.426'
  PACKAGE_PATH: ./src/**/*.nupkg
  NUGET_SERVER: https://api.nuget.org/v3/index.json


jobs:

  deploy-nuget:
    name: "Deploy nuget"
    runs-on: 'ubuntu-latest'

    steps:
    - name: "Checkout"
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.3.1
      with:
        global-json-file: 'global.json'
        dotnet-version: |
          ${{ env.SDK_VERSION_8 }}
          ${{ env.SDK_VERSION_7 }}
          ${{ env.SDK_VERSION_6 }}
          ${{ env.SDK_VERSION_5 }}
          ${{ env.SDK_VERSION_3 }}

    - name: "Restore dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build -c Release --no-restore

    - name: "Pack"
      run: dotnet pack -c Release --no-build

    - name: "Publish nuget"
      run: dotnet nuget push ${{ env.PACKAGE_PATH }} --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_SERVER }} --skip-duplicate
