name: 'Vulnerability Check'


on:
  workflow_dispatch:

  # Schedule to run every week on Sunday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'

  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main


env:
  SDK_VERSION_8: '8.0.404'
  SDK_VERSION_7: '7.0.410'
  SDK_VERSION_6: '6.0.428'
  SDK_VERSION_5: '5.0.408'
  SDK_VERSION_3: '3.1.426'


jobs:

  nuget-vulnerabilities-check:
    name: "NuGet vulnerabilities"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4.2.2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.3.1
      with:
        global-json-file: 'global.json'
        dotnet-version: |
          ${{ env.SDK_VERSION_8 }}
          ${{ env.SDK_VERSION_7 }}
          ${{ env.SDK_VERSION_6 }}
          ${{ env.SDK_VERSION_5 }}
          ${{ env.SDK_VERSION_3 }}

    - name: "Restore dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build --configuration Release --no-restore

    - name: "Checking NuGet vulnerabilities"
      run: |
        dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
        echo "Analyze dotnet list package command log output..."
        grep -q -i "\bcritical\b\|\bhigh\b\|\bmoderate\b\|\blow\b" build.log && { echo "Security Vulnerabilities found on the log output"; exit 1; } || exit 0
